apiVersion: v1
kind: Service
metadata:
  name: {{ include "sagitta-control.fullname" . }}-backend
  labels:
    {{- include "sagitta-control.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sagitta-control.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
