apiVersion: v2
name: sagitta-control
description: Sagitta Control 矢准数据库安全管控平台 — 企业级多引擎数据库安全管控平台
type: application
version: 2.3.5
appVersion: "2.3.5"

keywords:
  - database
  - sql-audit
  - dba
  - workflow

home: https://github.com/Lynn-Lee/Sagitta-Deploy
maintainers:
  - name: Sagitta Control Team

dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
